
site_name: Google Earth Engine (GEE) Research Apps
theme:
  name: material

nav:
  - Home: index.md
  - Applications:
      - Forest Watch: apps/forest.md
      - Urban Heat Map: apps/urban.md
  - About: about.md
